# Generated by Django 3.0.5 on 2020-04-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_project_clean_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='ratio',
            field=models.IntegerField(blank=True, default=75),
            preserve_default=False,
        ),
    ]
