# Generated by Django 3.0.5 on 2020-06-16 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import processing.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processing', '0004_auto_20200422_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('md_pk', models.FileField(upload_to=processing.models.pkl_path)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processing.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
