# Generated by Django 3.0.5 on 2020-06-16 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0005_alg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alg',
            name='project_id',
        ),
    ]
